<?xml version="1.0"?>
<package>
  <name>px4msgs</name>
  <version>0.0.0</version>
  <description>Px4 Ctrl Msgs</description>
  <maintainer email="lux@cqu.edu.cn">uav</maintainer>

  <license>GPLv3</license>


  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>cmake_modules</build_depend>
  <build_depend>message_generation</build_depend>

  <run_depend>message_runtime</run_depend>
  <run_depend>std_msgs</run_depend>
</package>
